### PR TITLE
Feature/responsive breakpoints

### PR DESCRIPTION
**Pull request by cremich**
@EmielH thanks for this awesome theme :) I used it for https://cremich.dev and made some css optimizations for mobile devices. 

The responsive media queries based on the default twitter bootstrap: https://getbootstrap.com/docs/4.0/layout/overview/#responsive-breakpoints

### CODE REVIEW

**Comment by EmielH** [comment]
Hi @cremich, thanks for taking the effort to create this pull request! I'm going to test this as soon as I have time. I would like to keep the SCSS files as clean as possible, so I'm not sure I would like to include the empty media queries. Is there a reason why you kept the empty media queries?

**Comment by cremich** [comment]
Of course, I understand. If you want I can remove these empty queries. 😊

They will be removed during the css compilation by sass. So the resulting css will not contain those empty queries. 

What I like about these bootstrap based queries: it is easy to understand what should be done if I want to optimize my css for several device types.

**Comment by EmielH** [comment]
Hi @cremich, I'm terribly sorry for the long delay. I finally got around to testing your pull request.

I like using Bootstrap's breakpoints as a starting point. I would, however, like to keep the original media queries (using `max-width: $break-large`). I see where Bootstrap is coming from, using `min-width`, starting at the smallest screen and then working their way up. Following their philosophy, however, requires a bit more refactoring of the styles, which I'm not sure is worth the effort at this point.

I like that you changed to font size to 6 rem on smaller devices; I agree that it looks better. Some of the other changes to styles, however, do not match the way the theme is intended to look. For example: the margin at the top of the page is gone.

I would propose to keep the breakpoints in `_variables.scss` and keep the change to the header font on smaller screens. Can you live with that?

**Comment by cremich** [comment]
@EmielH of course that is totally fine for me. How should be proceed? Will you cherry pick the relevant commits or should i interactive rebase this PR and drop the commits you do not want to merge.

**Comment by EmielH** [comment]
Maybe the easiest way is for me to make a new commit where I pick the changes I like from your commits. I would like to include some changes from both your commits. I would like to thank you for your contribution, and not burden you with all kinds of additional work. 🙂

**Comment by cremich** [comment]
@EmielH you are welcome. I am very happy with your theme. And I am also happy that you liked some of my changes. :)

**Comment by EmielH** [comment]
Thanks again for your contribution! :+1: See the commits above to see the changes that I've included.

**Pull request closed without merging**
