### PR TITLE
Add a default favicon 

### PR DESCRIPTION
**Pull request by cremich**
Added a small default favicon into the header section.

### CODE REVIEW

**Comment by EmielH** [comment]
Hi @cremich, thanks for using the theme and thanks for taking the effort to make this pull request! The favicon you created makes it look like the theme is aimed at developers, while I would like anyone to be able to use the theme. I'm in favor of including a favicon, but I would like it to be a more neutral one. Sorry! :pray:

**Comment by cremich** [comment]
No problem 😉 Thanks for your review. In my opinion an interesting feature would be:

Let the hello-theme user define what favicon he wants to use. So there should be a chance to override the favicon. 

What do you think about the following emoji as a default:

👋

**Comment by EmielH** [comment]
I love that suggestion! And since there's no favicon defined in the `<head>`, there is currently no option to use a favicon at all. That's a very good point. I would welcome a new PR if you have the time, otherwise I'll look into this myself. 🙂

**Comment by EmielH** [comment]
Hi @cremich, just to let you know: I just added the favicon you suggested.

**Pull request closed without merging**
